use atlas_common::crypto::hash::{Context, Digest};
use atlas_common::error::*;

use atlas_common::ordering::{Orderable, SeqNo};
use atlas_common::serialization_helper::NonSyncSerMsg;
use std::io::{Read, Write};
use std::mem::size_of;

/// The type abstraction for a monolithic state (only needs to be serializable, in reality)´
///
/// This represents one of the two available state implementations in Atlas.
/// It will be completely held in memory, therefore it is heavily limited in size.
/// It is, however, very fast and easy to use so it is recommended for small applications
/// Which have little state or for experiments.
///
/// For more complex state handling, see [`super::divisible_state::DivisibleState`]
///
pub trait MonolithicState: NonSyncSerMsg {
    ///Serialize a request from your service, given the writer to serialize into
    ///  (either for network sending or persistent storing)
    fn serialize_state<W>(w: W, request: &Self) -> Result<()>
    where
        W: Write;

    ///Deserialize a request that was generated by the serialize request function above
    ///  (either for network sending or persistent storing)
    fn deserialize_state<R>(r: R) -> Result<Self>
    where
        R: Read,
        Self: Sized;
}

pub struct InstallStateMessage<S> {
    seq: SeqNo,
    state: S,
}

pub struct AppStateMessage<S> {
    seq: SeqNo,
    state: S,
}

impl<S> AppStateMessage<S> {
    pub fn new(seq: SeqNo, state: S) -> Self {
        AppStateMessage { seq, state }
    }

    pub fn seq(&self) -> SeqNo {
        self.seq
    }

    pub fn state(&self) -> &S {
        &self.state
    }

    pub fn into_state(self) -> S {
        self.state
    }
}

impl<S> InstallStateMessage<S> {
    pub fn new(seq_no: SeqNo, state: S) -> Self {
        InstallStateMessage { seq: seq_no, state }
    }

    pub fn state(&self) -> &S {
        &self.state
    }

    pub fn into_state(self) -> S {
        self.state
    }
}

impl<S> Orderable for InstallStateMessage<S> {
    fn sequence_number(&self) -> SeqNo {
        self.seq
    }
}

pub fn digest_state<S: MonolithicState>(appstate: &S) -> Result<Digest> {
    let mut state_vec = Vec::with_capacity(size_of::<S>());

    S::serialize_state(&mut state_vec, appstate)?;

    let mut ctx = Context::new();

    ctx.update(&state_vec);

    let digest = ctx.finish();

    Ok(digest)
}
